safe:        false
auto:        true
server:      false
server_port: 4000

source:      /Users/framallo/workspace/blog
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    maruku
permalink:   date

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

exclude:
  - config.rb

